---

- hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  vars_prompt:
    - name: callsign
      prompt: what is your callsign
      private: no
    - name: nralias
      prompt: what is your netrom alias
      private: no
    - name: nrport
      prompt: what is your netrom port number
      default: "1"
    - name: nrpassword
      prompt: what is your netrom node password 
      private: yes
  roles:
    - role: ax25
      become: True
