---
galaxy_info:
  author: Max Lock
  description: Provisions Linux kernel based AX.25 packet radio networking and utilities
  license: GPL-3.0-only
  min_ansible_version: 2.1

  platforms:
    - name: debian
      versions:
        - all

  galaxy_tags:
    - ax25

  dependencies:
    - role: devoinc.systemd_service
      systemd_service:
        socat:
          enabled: Yes
          exec_start: "/usr/bin/socat PTY,link=/dev/direwolf,raw,echo=0,wait-slave TCP4:kvm:8001"
          restart: "always"
          wanted_by: "multi-user.target"
        kissattach:
          enabled: Yes
          exec_start: "/usr/sbin/kissattach /dev/direwolf ax0"
          restart: "on-failure"
          requisite: "socat.service"
          after: "socat.service"
          wanted_by: "multi-user.target"
        nrattach:
          enabled: Yes
          exec_start: "/usr/sbin/nrattach netrom"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
        mheard:
          enabled: Yes
          exec_start: "/usr/sbin/mheardd"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
        netrom:
          enabled: Yes
          exec_start: "/usr/sbin/netromd -i"
          restart: "on-failure"
          requisite: "nrattach.service"
          after: "nrattach.service"
          wanted_by: "multi-user.target"
        ax25d:
          enabled: Yes
          exec_start: "/usr/sbin/ax25d -l"
          restart: "on-failure"
          requisite: "kissattach.service"
          after: "kissattach.service"
          wanted_by: "multi-user.target"
